version: '3.8'

services:
  # Redis for session storage
  redis:
    image: redis:7-alpine
    container_name: mediconnect-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - mediconnect_network

  # PostgreSQL for persistent data storage
  postgres:
    image: postgres:15-alpine
    container_name: mediconnect-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mediconnect}
      POSTGRES_USER: ${POSTGRES_USER:-mediconnect_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_password_2024}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Migrations will be run manually via migrate.js script
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-mediconnect_user} -d ${POSTGRES_DB:-mediconnect}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - mediconnect_network
    profiles:
      - postgres  # Start with: docker-compose --profile postgres up

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  mediconnect_network:
    driver: bridge
